-- Schema for REST API
CREATE SCHEMA IF NOT EXISTS api AUTHORIZATION sis;
COMMENT ON SCHEMA api IS 'REST API tables';
ALTER DEFAULT PRIVILEGES FOR ROLE sis IN SCHEMA api GRANT SELECT ON TABLES TO sis_r;


------------------------------
-- Users and authentication --
------------------------------

-- Users - For human users who log in through the web application
CREATE TABLE IF NOT EXISTS api.user (
    user_id text PRIMARY KEY, -- e-mail/user_id
    password_hash text NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at timestamp DEFAULT CURRENT_DATE,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    last_login timestamp
);
COMMENT ON TABLE api.user IS 'For human users who log in through the web application';
ALTER TABLE IF EXISTS api.user OWNER to sis;
GRANT SELECT ON TABLE api.user TO sis_r;

-- API_client - For server-to-server authentication
CREATE TABLE IF NOT EXISTS api.api_client (
    api_client_id text,
    api_key text NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at date DEFAULT CURRENT_DATE,
    expires_at date,
    last_login timestamp,
    description text NOT NULL DEFAULT '',
    CONSTRAINT api_client_id_pkey PRIMARY KEY (api_client_id),
    CONSTRAINT api_client_api_key_key UNIQUE (api_key)
);
COMMENT ON TABLE api.api_client IS 'For server-to-server authentication';
ALTER TABLE IF EXISTS api.api_client OWNER to sis;
GRANT SELECT ON TABLE api.api_client TO sis_r;

-- Audit - Track authentication attempts and API usage
CREATE TABLE IF NOT EXISTS api.audit (
    audit_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id text,
    api_client_id text,
    action text,
    details jsonb,
    ip_address inet,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_pkey PRIMARY KEY (audit_id),
    CONSTRAINT audit_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES api.user (user_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT audit_api_client_id_fkey FOREIGN KEY (api_client_id)
        REFERENCES api.api_client (api_client_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);
COMMENT ON TABLE api.audit IS 'Track authentication attempts and API usage';
ALTER TABLE IF EXISTS api.audit OWNER to sis;
GRANT SELECT ON TABLE api.audit TO sis_r;


-------------------------------
-- Application costumization --
-------------------------------

-- Application settings
CREATE TABLE IF NOT EXISTS api.setting (
    key text PRIMARY KEY,
    value text
);
ALTER TABLE IF EXISTS api.setting OWNER to sis;
GRANT SELECT ON TABLE api.setting TO sis_r;

-- Layer management
CREATE TABLE IF NOT EXISTS api.layer (
    project_id text,
    project_name text,
    layer_id text PRIMARY KEY,
    publish BOOLEAN DEFAULT TRUE,
    property_name text,
    dimension text,
    version text,
    unit_of_measure_id text REFERENCES soil_data.unit_of_measure(unit_of_measure_id),
    metadata_url text,
    download_url text,
    get_map_url text,
    get_legend_url text,
    get_feature_info_url text
);
ALTER TABLE IF EXISTS api.layer OWNER to sis;
GRANT SELECT ON TABLE api.layer TO sis_r;


------------------------------------
-- Client REST API endpoint views --
------------------------------------

-- view to expose the list of soil properties and geographical extent
CREATE OR REPLACE VIEW api.vw_api_manifest AS
SELECT 
    'Portugal SIS' AS sis,
    opc.property_phys_chem_id AS property,
    COUNT(DISTINCT p.profile_id) AS profiles,
    COUNT(rpc.result_phys_chem_id) AS observations,
    ST_Envelope(ST_Collect(plt."position")) AS geom
FROM soil_data.observation_phys_chem opc
    INNER JOIN soil_data.result_phys_chem rpc ON opc.observation_phys_chem_id = rpc.observation_phys_chem_id
    INNER JOIN soil_data.specimen s ON rpc.specimen_id = s.specimen_id
    INNER JOIN soil_data.element e ON s.element_id = e.element_id
    INNER JOIN soil_data.profile p ON e.profile_id = p.profile_id
    INNER JOIN soil_data.plot plt ON p.plot_id = plt.plot_id
GROUP BY opc.property_phys_chem_id
ORDER BY opc.property_phys_chem_id;
COMMENT ON VIEW api.vw_api_manifest IS 'View to expose the list of soil properties and geographical extent';
ALTER TABLE IF EXISTS api.vw_api_manifest OWNER to sis;
GRANT SELECT ON TABLE api.vw_api_manifest TO sis_r;


-- view to expose the list of profiles
CREATE OR REPLACE VIEW api.vw_api_profiles AS
SELECT 
    proj.name AS project_name,
    p.profile_code,
    plt.altitude,
    plt.time_stamp AS date,
    ST_AsGeoJSON(plt."position")::json AS geometry
FROM soil_data.profile p
    INNER JOIN soil_data.plot plt ON p.plot_id = plt.plot_id
    INNER JOIN soil_data.site s ON plt.site_id = s.site_id
    LEFT JOIN soil_data.project_site ps ON s.site_id = ps.site_id
    LEFT JOIN soil_data.project proj ON ps.project_id = proj.project_id
WHERE plt."position" IS NOT NULL
ORDER BY p.profile_id;
COMMENT ON VIEW api.vw_api_profiles IS 'View to expose the list of profiles';
ALTER TABLE IF EXISTS api.vw_api_profiles OWNER to sis;
GRANT SELECT ON TABLE api.vw_api_profiles TO sis_r;


-- view to expose the observational data
CREATE OR REPLACE VIEW api.vw_api_observations AS
SELECT p3.profile_code,
    e.upper_depth,
    e.lower_depth,
    o.property_phys_chem_id,
    o.procedure_phys_chem_id,
    o.unit_of_measure_id,
    r.value
   FROM soil_data.project p
     LEFT JOIN soil_data.project_site sp ON sp.project_id = p.project_id
     LEFT JOIN soil_data.site s ON s.site_id = sp.site_id
     LEFT JOIN soil_data.plot p2 ON p2.site_id = s.site_id
     LEFT JOIN soil_data.profile p3 ON p3.plot_id = p2.plot_id
     LEFT JOIN soil_data.element e ON e.profile_id = p3.profile_id
     LEFT JOIN soil_data.specimen s2 ON s2.element_id = e.element_id
     LEFT JOIN soil_data.result_phys_chem r ON r.specimen_id = s2.specimen_id
     LEFT JOIN soil_data.observation_phys_chem o ON o.observation_phys_chem_id = r.observation_phys_chem_id
  ORDER BY p3.profile_code, e.upper_depth, o.property_phys_chem_id;
COMMENT ON VIEW api.vw_api_observations IS 'View to expose the observational data';
ALTER TABLE IF EXISTS api.vw_api_observations OWNER to sis;
GRANT SELECT ON TABLE api.vw_api_observations TO sis_r;

-- view with the layers to be displayed in web mapping
-- CREATE OR REPLACE VIEW api.vw_api_layers AS
-- SELECT  p.project_name, 
--         l.layer_id, 
--         p2.property_id, 
--         p2.name property_name, 
--         p2.unit_of_measure_id, 
--         l.dimension_depth || ' '||l.dimension_stats AS dimension_des, 
--         'http://localhost:8001/collections/metadata:main/items/'||m.file_identifier metadata_url, 
--         u.url download_url,
--         'http://localhost:8082/?map=/etc/mapserver/'||l.layer_id||'.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX='||l.south_bound_latitude||'%2C'||l.west_bound_longitude||'%2C'||l.north_bound_latitude||'%2C'||l.east_bound_longitude||'&CRS=EPSG%3A4326&WIDTH='||l.raster_size_x||'&HEIGHT='||l.raster_size_y||'&LAYERS='||l.layer_id||'&STYLES=&FORMAT=image%2Fpng&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi%3A96&TRANSPARENT=TRUE' get_map_url,
--         'http://localhost:8082/?map=/etc/mapserver/'||l.layer_id||'.map&SERVICE=WMS&VERSION=1.1.1&LAYER='||l.layer_id||'&REQUEST=getlegendgraphic&FORMAT=image/png' get_legend_url,
--         'http://localhost:8082/?map=/etc/mapserver/'||l.layer_id||'.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&LAYERS='||l.layer_id||'&STYLES=&FORMAT=image%2Fpng&QUERY_LAYERS='||l.layer_id||'&INFO_FORMAT=text%2Fhtml&I=282&J=429' get_feature_info_url
-- FROM spatial_metadata.layer l
-- LEFT JOIN spatial_metadata.mapset m ON m.mapset_id = l.mapset_id
-- LEFT JOIN spatial_metadata.project p ON p.country_id = m.country_id AND p.project_id = m.project_id
-- LEFT JOIN spatial_metadata.property p2 ON p2.property_id = m.property_id 
-- LEFT JOIN spatial_metadata.url u ON u.mapset_id = m.mapset_id AND u.url_name = 'Download '||l.dimension_depth || ' '||l.dimension_stats
-- WHERE m.country_id = '$COUNTRY_ID'
-- ORDER BY p.project_name, l.layer_id;
-- ALTER TABLE IF EXISTS api.vw_api_layers OWNER to sis;
-- GRANT SELECT ON TABLE api.vw_api_layers TO sis_r;


------------------
-- Data upload  --
------------------

CREATE SCHEMA IF NOT EXISTS soil_data_upload AUTHORIZATION sis;
COMMENT ON SCHEMA soil_data_upload IS 'Schema to upload soil data';
ALTER DEFAULT PRIVILEGES FOR ROLE sis IN SCHEMA soil_data_upload GRANT SELECT ON TABLES TO sis_r;


CREATE TABLE IF NOT EXISTS api.uploaded_dataset (
    user_id text,
    project_id text,
    table_name text PRIMARY KEY,
    file_name TEXT NOT NULL UNIQUE,
    upload_date DATE DEFAULT CURRENT_DATE,
    ingestion_date date,
    status text,
    depth_if_topsoil smallint,
    n_rows integer,
    n_col smallint,
    has_cords boolean,
    cords_epsg integer,
    cords_check boolean DEFAULT false,
    note text,
    CONSTRAINT uploaded_dataset_status_check CHECK (status = ANY (ARRAY['Uploaded', 'Ingested', 'Removed'])),
    CONSTRAINT uploaded_dataset_project_id_fkey FOREIGN KEY (project_id)
        REFERENCES soil_data.project (project_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT uploaded_dataset_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES api.user (user_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);
ALTER TABLE IF EXISTS api.uploaded_dataset OWNER to sis;
GRANT SELECT ON TABLE api.uploaded_dataset TO sis_r;


CREATE TABLE IF NOT EXISTS api.uploaded_dataset_column
(
    table_name text NOT NULL,
    column_name text NOT NULL,
    property_phys_chem_id text,
    procedure_phys_chem_id text,
    unit_of_measure_id text,
    ignore_column boolean DEFAULT false,
    note text,
    CONSTRAINT uploaded_dataset_column_pkey PRIMARY KEY (table_name, column_name),
    CONSTRAINT uploaded_dataset_column_table_name_fkey FOREIGN KEY (table_name)
        REFERENCES api.uploaded_dataset (table_name) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT uploaded_dataset_column_property_phys_chem_id_fkey FOREIGN KEY (property_phys_chem_id)
        REFERENCES soil_data.property_phys_chem (property_phys_chem_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT uploaded_dataset_column_procedure_phys_chem_id_fkey FOREIGN KEY (procedure_phys_chem_id)
        REFERENCES soil_data.procedure_phys_chem (procedure_phys_chem_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT uploaded_dataset_column_unit_of_measure_id_fkey FOREIGN KEY (unit_of_measure_id)
        REFERENCES soil_data.unit_of_measure (unit_of_measure_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);
ALTER TABLE IF EXISTS api.uploaded_dataset_column OWNER to sis;
GRANT SELECT ON TABLE api.uploaded_dataset_column TO sis_r;
