#!/bin/bash

###############################################
#                    Rename                   #
###############################################

echo

COUNTRY=BD
PROJ=GSAS
YEAR=2021
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                   # << EDIT THIS LINE!
OUTPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/tmp"                          # << EDIT THIS LINE!

mkdir -p "$OUTPUT_DIR"

# # Non existing NoData parameter, add now or fail after.
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_ECseMap030-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_ECseMap30100-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_ECuncertaintyMap030-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_ECuncertaintyMap30100-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_ESPMap030-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_ESPMap30100-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_ESPuncertaintyMap030-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_ESPuncertaintyMap30100-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_pHMap030-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_pHMap30100-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_pHuncertaintyMap030-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_pHuncertaintyMap30100-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_SaltMap030-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_SaltMap30100-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_UncertaintySaltMap030-Arifunnahar_akhi.tif
# gdal_edit.py -a_nodata nan $INPUT_DIR/BGD_UncertaintySaltMap30100-Arifunnahar_akhi.tif

# cp $INPUT_DIR/BGD_ECseMap030-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-0-30-MEAN.tif
# cp $INPUT_DIR/BGD_ECseMap30100-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-30-100-MEAN.tif
# cp $INPUT_DIR/BGD_ECuncertaintyMap030-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-0-30-UNCT.tif
# cp $INPUT_DIR/BGD_ECuncertaintyMap30100-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-30-100-UNCT.tif
# cp $INPUT_DIR/BGD_ESPMap030-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXC-$YEAR-0-30-MEAN.tif
# cp $INPUT_DIR/BGD_ESPMap30100-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXC-$YEAR-30-100-MEAN.tif
# cp $INPUT_DIR/BGD_ESPuncertaintyMap030-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXC-$YEAR-0-30-UNCT.tif
# cp $INPUT_DIR/BGD_ESPuncertaintyMap30100-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXC-$YEAR-30-100-UNCT.tif
# cp $INPUT_DIR/BGD_pHMap030-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-0-30-MEAN.tif
# cp $INPUT_DIR/BGD_pHMap30100-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-30-100-MEAN.tif
# cp $INPUT_DIR/BGD_pHuncertaintyMap030-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-0-30-UNCT.tif
# cp $INPUT_DIR/BGD_pHuncertaintyMap30100-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-30-100-UNCT.tif
# cp $INPUT_DIR/BGD_SaltMap030-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SALT-$YEAR-0-30-MEAN.tif
# cp $INPUT_DIR/BGD_SaltMap30100-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SALT-$YEAR-30-100-MEAN.tif
# cp $INPUT_DIR/BGD_UncertaintySaltMap030-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SALT-$YEAR-0-30-UNCT.tif
# cp $INPUT_DIR/BGD_UncertaintySaltMap30100-Arifunnahar_akhi.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SALT-$YEAR-30-100-UNCT.tif


PROJ=GSNM
YEAR=2024
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                 # << EDIT THIS LINE!

cp $INPUT_DIR/BGD_class_peat.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PEAT-$YEAR-0-0-MEAN.tif
cp $INPUT_DIR/BGD_probability_peat.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PEAT-$YEAR-0-0-PROB.tif
cp $INPUT_DIR/BGD_mean_bd_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_bd_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_bd_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_mean_caco3_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CACO3ET-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_caco3_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CACO3ET-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_caco3_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CACO3ET-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_mean_cec_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_cec_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_cec_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_mean_clay_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_clay_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_clay_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_mean_ec_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_ec_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_ec_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_mean_ocs_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGS-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_ocs_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGS-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_ocs_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGS-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_mean_ph_0_10.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-0-10-MEAN.tif
cp $INPUT_DIR/BGD_mean_ph_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_ph_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_ph_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_mean_sand_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_sand_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_sand_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_mean_silt_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_silt_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_silt_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_mean_soc_0_10.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-0-10-MEAN.tif
cp $INPUT_DIR/BGD_mean_soc_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_soc_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_soc_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_mean_tn_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/BGD_mean_tn_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/BGD_mean_tn_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-60-120-MEAN.tif
cp $INPUT_DIR/BGD_sd_bd_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_bd_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_bd_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-60-120-SDEV.tif
cp $INPUT_DIR/BGD_sd_caco3_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CACO3ET-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_caco3_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CACO3ET-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_caco3_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CACO3ET-$YEAR-60-120-SDEV.tif
cp $INPUT_DIR/BGD_sd_cec_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_cec_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_cec_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-60-120-SDEV.tif
cp $INPUT_DIR/BGD_sd_clay_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_clay_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_clay_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-60-120-SDEV.tif
cp $INPUT_DIR/BGD_sd_ec_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_ec_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_ec_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-60-120-SDEV.tif
cp $INPUT_DIR/BGD_sd_ocs_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGS-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_ocs_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGS-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_ocs_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGS-$YEAR-60-120-SDEV.tif
cp $INPUT_DIR/BGD_sd_ph_0_10.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-0-10-SDEV.tif
cp $INPUT_DIR/BGD_sd_ph_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_ph_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_ph_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-60-120-SDEV.tif
cp $INPUT_DIR/BGD_sd_sand_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_sand_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_sand_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-60-120-SDEV.tif
cp $INPUT_DIR/BGD_sd_silt_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_silt_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_silt_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-60-120-SDEV.tif
cp $INPUT_DIR/BGD_sd_soc_0_10.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-0-10-SDEV.tif
cp $INPUT_DIR/BGD_sd_soc_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_soc_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_soc_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-60-120-SDEV.tif
cp $INPUT_DIR/BGD_sd_tn_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-0-30-SDEV.tif
cp $INPUT_DIR/BGD_sd_tn_30_60.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-30-60-SDEV.tif
cp $INPUT_DIR/BGD_sd_tn_60_120.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-60-120-SDEV.tif


PROJ=GSOCSEQ
YEAR=2022
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                 # << EDIT THIS LINE!

cp $INPUT_DIR/BGD_GSOCseq_AbsDiff_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_AbsDiff_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_AbsDiff_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_AbsDiff_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_ASR_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_ASR_BAU_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAU-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_ASR_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_ASR_SSM1_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_ASR_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_ASR_SSM2_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_ASR_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_ASR_SSM3_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_BAU_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAU-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_finalSOC_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_finalSOC_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_finalSOC_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_finalSOC_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_RelDiff_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_RelDiff_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_RelDiff_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_RSR_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_RSR_SSM1_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_RSR_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_RSR_SSM2_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_RSR_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_RSR_SSM3_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/BGD_GSOCseq_T0_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BGD_GSOCseq_T0_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0-$YEAR-$UD-$LD-UNCT.tif
