-- create roles
CREATE ROLE sis_r WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD 'sis';
CREATE ROLE pycsw WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD 'pycsw';
ALTER ROLE pycsw SET search_path = spatial_metadata;
CREATE ROLE kobo WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD 'kobo';
ALTER ROLE kobo SET search_path = kobo;

-- add extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA public;
CREATE EXTENSION IF NOT EXISTS postgis_raster SCHEMA public;
CREATE EXTENSION IF NOT EXISTS postgis_sfcgal SCHEMA public;

-- remove extensions
DROP EXTENSION postgis_tiger_geocoder;
DROP EXTENSION postgis_topology;
DROP EXTENSION fuzzystrmatch;
DROP SCHEMA IF EXISTS tiger;
DROP SCHEMA IF EXISTS tiger_data;
DROP SCHEMA IF EXISTS topology;
