--
-- PostgreSQL database dump
--

\restrict 8c5omkiKrN1PJQDBkRDt5eZKJ4fbiOg4Lp0TUxlStEgL7qQIAeGhrUprgNPixjM

-- Dumped from database version 12.22 (Ubuntu 12.22-3.pgdg22.04+1)
-- Dumped by pg_dump version 18.3 (Ubuntu 18.3-1.pgdg22.04+1)

-- Started on 2026-05-09 10:48:07 CEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3997 (class 0 OID 54916003)
-- Dependencies: 220
-- Data for Name: property; Type: TABLE DATA; Schema: soil_data; Owner: sis
--

INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SOLSAL', 'Soluble salts', NULL, NULL, 'SOLSAL', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",salinity}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ECEC', 'Cation exchange capacity effective', NULL, NULL, 'ECEC', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","effective cation exchange capacity"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRSRSSM2', 'Relative sequestration rate sustainable soil management 2', 0, 706.39966, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('GYP', 'Gypsum content - weight', NULL, NULL, 'GYP', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",gypsum}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PEAT', 'Peat', 0, 1, NULL, 'categorical', 4, '#CA0020', '#3F68E2', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CARINORG', 'Carbon (C) - inorganic', NULL, NULL, 'CARINORG', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","inorganic carbon",carbon}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BULDWHOLE', 'Bulk Density whole soil', NULL, NULL, 'BULDWHOLE', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","bulk density"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRDSSM1', 'Relative difference sustainable soil management 1', 0, 10.117194, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGASRBAU', 'Absolute sequestration rate business-as-usual', -49.95, 999, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ALUTOT', 'Aluminium (Al) total', NULL, NULL, 'ALUTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",aluminium,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGADSSM1', 'Absolute difference sustainable soil management 1', -41.437344, 35.42143, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGSOCBAU', 'Final SOC stocks after 20 years business-as-usual', 1.9685694, 299.9769, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('POR', 'Porosity', NULL, NULL, 'POR', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",porosity}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CARSTK', 'Carbon (C) - organic stock', 5.227511, 878.3219, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CARORG', 'Carbon (C) - organic', 0.102681465, 32.575752, 'CARORG', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGASRSSM2', 'Absolute sequestration rate sustainable soil management 2', -49.95, 999, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CAD', 'Cadmium (Cd)', NULL, NULL, 'CAD', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",cadmium,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('TEXTCLAY', 'Clay texture fraction', 2.0954218, 67.95525, 'TEXTCLAY', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",clay,texture}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('HYDCOND', 'Hydraulic conductivity', NULL, NULL, 'HYDCOND', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","hydraulic conductivity"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MOL', 'Molybdenum (Mo)', NULL, NULL, 'MOL', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",molybdenum,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGSOCSSM2', 'Final SOC stocks after 20 years sustainable soil management 2', 2.0859761, 299.99915, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGSOCSSM1', 'Final SOC stocks after 20 years sustainable soil management 1', 2.027273, 299.9997, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGADSSM3', 'Absolute difference sustainable soil management 3', -26.77324, 39.72415, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGSOCSSM3', 'Final SOC stocks after 20 years sustainable soil management 3', 2.203362, 299.99362, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGT0', 'Initial SOC stocks at year 2020 time zero', 0, 544.3276, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGASRSSM1', 'Absolute sequestration rate sustainable soil management 1', -49.95, 999, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ORGMAT', 'Organic matter', 0.1361388, 83.30734, 'ORGMAT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic matter"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRSRSSM3', 'Relative sequestration rate sustainable soil management 3', 0, 706.39966, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PHO', 'Phosphorus (P)', 1.18992, 414.6663, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",phosphorus,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SODEXP', 'Sodium (Na+) - exchangeable', 0.009701022, 23.825006, 'SODEXP', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","exchangeable sodium",salinity}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SALT', 'Salinification', 0.050008815, 8, NULL, 'categorical', 4, '#CA0020', '#3F68E2', '{soil,"digital soil mapping","exchangeable sodium",salinity}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('TEXTSAND', 'Sand texture fraction', 3.99434, 74.868645, 'TEXTSAND', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",sand,texture}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CEC', 'Cation exchange capacity', 1.1099763, 161.03993, 'CEC', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","cation exchange capacity"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRDSSM2', 'Relative difference sustainable soil management 2', 0, 19.435438, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGADSSM2', 'Absolute difference sustainable soil management 2', -36.54917, 29.71708, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGADBAU', 'Absolute difference business-as-usual', -46.325394, 30.290558, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BULDFINE', 'Bulk Density of the fine earth fraction', 0.017327346, 1.5635105, 'BULDFINE', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","bulk density"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRDSSM3', 'Relative difference sustainable soil management 3', 0, 36.01025, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGASRSSM3', 'Absolute sequestration rate sustainable soil management 3', -49.95, 999, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PHX', 'pH - Hydrogen potential', 0, 37.61572, 'PH', 'quantitative', 10, '#CA0020', '#3F68E2', '{soil,"digital soil mapping",ph}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRSRSSM1', 'Relative sequestration rate sustainable soil management 1', 0, 706.39966, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ACIEXC', 'Exchangeable acidity', NULL, NULL, 'ACIEXC', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",acidity}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CCETOT', 'Calcium carbonate equivalent - total', 0.0022378669, 9.722537, 'CCETOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ALUEXC', 'Aluminium (Al+++) - exchangeable', NULL, NULL, 'ALUEXC', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",aluminium,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BASCAL', 'Base saturation', 5.24108, 310.83453, 'BASCAL', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","base saturation"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BOREXT', 'Boron (B) - extractable', NULL, NULL, 'BOREXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",boron,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('AVAVOL', 'Available water capacity - volumetric', NULL, NULL, 'AVAVOL', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","water capacity"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BASEXC', 'Exchangeable bases', 1.25032, 38.72092, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","exchangeable bases"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BORTOT', 'Boron (B) - total', NULL, NULL, 'BORTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",boron,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BSATS', 'Base saturation - sum of cations DELETE!', 0.5860444, 21.523035, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","base saturation"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CALEXT', 'Calcium (Ca++) - extractable', NULL, NULL, 'CALEXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CALTOT', 'Calcium (Ca++) - total', NULL, NULL, 'CALTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CALEXC', 'Calcium (Ca++) - exchangeable', 0.64788485, 31.82854, 'CALEXC', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CLAWRB', 'World reference base', 1, 7, NULL, 'categorical', 7, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","soil classification",wrb}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('COAFRAF', 'Coarse fragments - field class', 6.5923385e-05, 47.75318, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","coarse fragments"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('COAFRA', 'Coarse fragments', 0.55474, 47.75318, 'COAFRA', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","coarse fragments"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CARNIT', 'Carbon Nitrogen ratio', 1.165, 129.77734, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",carbon,nitrogen}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CARTOT', 'Carbon (C) - total', NULL, NULL, 'CARTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ELECCOND', 'Electrical conductivity', 0.00038286045, 23.560993, 'ELECCOND', 'quantitative', 10, '#CA0020', '#3F68E2', '{soil,"digital soil mapping","electrical conductivity"}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('COPEXT', 'Copper (Cu) - extractable', NULL, NULL, 'COPEXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",copper,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('COPTOT', 'Copper (Cu) - total', NULL, NULL, 'COPTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",copper,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('IROEXT', 'Iron (Fe) - extractable', NULL, NULL, 'IROEXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",iron,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('IROTOT', 'Iron (Fe) - total', NULL, NULL, 'IROTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",iron,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('POTEXC', 'Potassium (K+) - exchangeable', 0.23427553, 478.14163, 'POTEXC', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",potassium,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('POTEXT', 'Potassium (K) - extractable', 4.5881696, 1249.2526, 'POTEXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",potassium,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('HYDEXC', 'Hydrogen (H+) - exchangeable', NULL, NULL, 'HYDEXC', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",hydrogen}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('POTTOT', 'Potassium (K) - total', 9.02848, 756.61646, 'POTTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",potassium,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('POT', 'Potassium (K)', 0.16248894, 756.61646, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",potassium,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MAGEXT', 'Magnesium (Mg) - extractable', NULL, NULL, 'MAGEXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",magnesium,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MAGEXC', 'Magnesium (Mg++) - exchangeable', 0.1713, 7.6219, 'MAGEXC', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",magnesium,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MAGTOT', 'Magnesium (Mg) - total', NULL, NULL, 'MAGTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",magnesium,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MANEXT', 'Manganese (Mn) - extractable', NULL, NULL, 'MANEXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",manganese,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MANTOT', 'Manganese (Mn) - total', NULL, NULL, 'MANTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",manganese,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('NITTOT', 'Nitrogen (N) - total', 0.023296468, 37738.81, 'NITTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",nitrogen,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SODEXT', 'Sodium (Na) - extractable', NULL, NULL, 'SODEXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","exchangeable sodium",salinity}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SODTOT', 'Sodium (Na) - total', NULL, NULL, 'SODTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","exchangeable sodium",salinity}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PHORET', 'Phosphorus (P) - retention', NULL, NULL, 'PHORET', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",phosphorus,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PHOEXT', 'Phosphorus (P) - extractable', 7.6332707, 336.86963, 'PHOEXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",phosphorus,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PHAQ', 'pH - Hydrogen potential in water DELETE!', 3.5527137e-15, 38.24991, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",pH}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PHOTOT', 'Phosphorus (P) - total', 1.18992, 414.6663, 'PHOTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",phosphorus,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SULEXT', 'Sulfur (S) - extractable', NULL, NULL, 'SULEXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",sulfur,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('TEXTSILT', 'Silt texture fraction', 3.2109754, 76.15516, 'TEXTSILT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",silt,texture}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SULTOT', 'Sulfur (S) - total', NULL, NULL, 'SULTOT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",sulfur,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ZINEXT', 'Zinc (Zn) - extractable', NULL, NULL, 'ZINEXT', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",zinc,nutrient}');
INSERT INTO soil_data.mapped_property (mapped_property_id, name, min, max, property_num_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ZNTOT', 'Zinc (Zn) - total', NULL, NULL, 'ZIN', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",zinc,nutrient}');


-- Completed on 2026-05-09 10:48:07 CEST

--
-- PostgreSQL database dump complete
--

\unrestrict 8c5omkiKrN1PJQDBkRDt5eZKJ4fbiOg4Lp0TUxlStEgL7qQIAeGhrUprgNPixjM

