# Procedures (275 rows)
SPARQL
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
SELECT ?query
WHERE {
    GRAPH <http://w3id.org/glosis/model/procedure> {
        ?uri a skos:Concept .
        ?uri skos:prefLabel ?label .    
        OPTIONAL {?uri skos:broader ?broader} .
    }
    BIND (CONCAT('INSERT INTO soil_data.procedure_num (uri, procedure_num_id, broader_id) VALUES (\'', STR(?uri),
         '\', \'', ?label, '\', (SELECT procedure_num_id FROM soil_data.procedure_num WHERE uri LIKE \'', 
         COALESCE(STR(?broader), ''), '\'));') AS ?query)
};