#!/bin/bash

###############################################
#                    Rename                   #
###############################################

echo

COUNTRY=VN
PROJ=GSAS
YEAR=2021
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                   # << EDIT THIS LINE!
OUTPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/tmp"                          # << EDIT THIS LINE!

mkdir -p "$OUTPUT_DIR"

# Non existing NoData parameter, add now or fail after.
gdal_edit.py -a_nodata 0 $INPUT_DIR/Top0_30ECse_VN.tif
gdal_edit.py -a_nodata 0 $INPUT_DIR/Top0_30ESP_VN.tif
gdal_edit.py -a_nodata 0 $INPUT_DIR/Top0_30saltaffected_VN.tif

cp $INPUT_DIR/Top0_30ECse_VN.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Top0_30ESP_VN.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXC-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Top0_30saltaffected_VN.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SALT-$YEAR-$UD-$LD-MEAN.tif


PROJ=GSNM
YEAR=2024
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                   # << EDIT THIS LINE!

cp $INPUT_DIR/VNM_mean_avai_k2o_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-KEXT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_avai_p2o5_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PEXT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_base_sat_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BASAT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_bd_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_cec_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_clay_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_crf_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CFRAGF-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_ec_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_ocs_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGS-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_ph_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_sand_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_silt_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_sum_bases_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BSATS-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_total_k2o_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-KTOT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_total_n_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_total_oc_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_mean_total_p2o5_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PTOT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_sd_avai_k2o_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-KEXT-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_avai_p2o5_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PEXT-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_base_sat_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BASAT-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_bd_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_cec_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_clay_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_crf_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CFRAGF-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_ec_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_ocs_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGS-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_ph_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_sand_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_silt_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_sum_bases_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BSATS-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_total_k2o_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-KTOT-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_total_n_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_total_oc_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/VNM_sd_total_p2o5_0_30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PTOT-$YEAR-$UD-$LD-SDEV.tif


PROJ=GSOCSEQ
YEAR=2022
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                 # << EDIT THIS LINE!

cp $INPUT_DIR/VNM_GSOCseq_AbsDiff_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_AbsDiff_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_AbsDiff_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_AbsDiff_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_ASR_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_ASR_BAU_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAU-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_ASR_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_ASR_SSM1_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_ASR_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_ASR_SSM2_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_ASR_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_ASR_SSM3_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_BAU_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAU-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_finalSOC_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_finalSOC_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_finalSOC_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_finalSOC_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_RelDiff_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_RelDiff_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_RelDiff_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_RSR_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_RSR_SSM1_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_RSR_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_RSR_SSM2_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_RSR_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_RSR_SSM3_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/VNM_GSOCseq_T0_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/VNM_GSOCseq_T0_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0-$YEAR-$UD-$LD-UNCT.tif
