#!/bin/bash

###############################################
#                    Rename                   #
###############################################

echo

COUNTRY=TH
PROJ=GSNM
YEAR=2025
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                   # << EDIT THIS LINE!
OUTPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/tmp"                          # << EDIT THIS LINE!

mkdir -p "$OUTPUT_DIR"

cp $INPUT_DIR/TH-$PROJ-AKX-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TH-$PROJ-AKXSD-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-$UD-$LD-SDEV.tif 
cp $INPUT_DIR/TH-$PROJ-APX-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TH-$PROJ-APXSD-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-$UD-$LD-SDEV.tif 
cp $INPUT_DIR/TH-$PROJ-BDX-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TH-$PROJ-BDXSD-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/TH-$PROJ-CEC-2024-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TH-$PROJ-CECSD-2024-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/TH-$PROJ-PHX-2024-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TH-$PROJ-PHXSD-2024-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-$UD-$LD-SDEV.tif
