-- OBJECT: all
-- ISSUE: add only SELECT user privileges


ALTER DEFAULT PRIVILEGES FOR ROLE sis IN SCHEMA core GRANT SELECT ON TABLES TO sis_r;
ALTER DEFAULT PRIVILEGES FOR ROLE sis IN SCHEMA metadata GRANT SELECT ON TABLES TO sis_r;
ALTER SCHEMA public OWNER TO sis;
