-- OBJECT: new
-- ISSUE: implementation of ISO28258 class Soil Mapping (polygon maps)


-- ----------------------------------------------------------------------------
-- SoilMap: A soil map (collection of mapping units)
-- ----------------------------------------------------------------------------
CREATE TABLE soil_data.soil_map (
    soil_map_id         INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) PRIMARY KEY,
    name                TEXT NOT NULL,
    description         TEXT,
    scale_denominator   INTEGER,
    spatial_resolution_m NUMERIC(10,2),
    publication_date    DATE,
    remarks             TEXT,
    geom                GEOMETRY(Polygon, 4326)
);
ALTER TABLE IF EXISTS soil_data.soil_map OWNER to sis;
REVOKE ALL ON TABLE soil_data.soil_map FROM sis_r;
GRANT ALL ON TABLE soil_data.soil_map TO sis;
GRANT SELECT ON TABLE soil_data.soil_map TO sis_r;

COMMENT ON TABLE soil_data.soil_map IS 'A soil map containing delineated mapping units (ISO 28258 SoilMap feature)';
COMMENT ON COLUMN soil_data.soil_map.soil_map_id IS 'Unique identifier for the soil map';
COMMENT ON COLUMN soil_data.soil_map.name IS 'Name of the soil map';
COMMENT ON COLUMN soil_data.soil_map.description IS 'Detailed description of the soil map';
COMMENT ON COLUMN soil_data.soil_map.scale_denominator IS 'Map scale denominator (e.g., 50000 for 1:50,000)';
COMMENT ON COLUMN soil_data.soil_map.spatial_resolution_m IS 'Spatial resolution in meters';
COMMENT ON COLUMN soil_data.soil_map.publication_date IS 'Date when the map was published';
COMMENT ON COLUMN soil_data.soil_map.remarks IS 'Additional remarks or notes';
COMMENT ON COLUMN soil_data.soil_map.geom IS 'Polygon geometry representing the map extent (EPSG:4326)';

CREATE INDEX idx_soil_map_geom ON soil_data.soil_map USING GIST (geom);
COMMENT ON INDEX soil_data.idx_soil_map_geom IS 'Spatial index on soil map extent geometry';


-- ----------------------------------------------------------------------------
-- Project <-> SoilMap: relatedMap (0..* to 0..*)
-- ----------------------------------------------------------------------------
CREATE TABLE soil_data.project_soil_map (
    project_id          TEXT REFERENCES soil_data.project(project_id) ON DELETE CASCADE,
    soil_map_id         INTEGER REFERENCES soil_data.soil_map(soil_map_id) ON DELETE CASCADE,
    remarks             TEXT,
    PRIMARY KEY (project_id, soil_map_id)
);
ALTER TABLE IF EXISTS soil_data.project_soil_map OWNER to sis;
REVOKE ALL ON TABLE soil_data.project_soil_map FROM sis_r;
GRANT ALL ON TABLE soil_data.project_soil_map TO sis;
GRANT SELECT ON TABLE soil_data.project_soil_map TO sis_r;

COMMENT ON TABLE soil_data.project_soil_map IS 'Links soil maps to projects (relatedMap many-to-many)';
COMMENT ON COLUMN soil_data.project_soil_map.project_id IS 'Reference to the project';
COMMENT ON COLUMN soil_data.project_soil_map.soil_map_id IS 'Reference to the soil map (relatedMap)';
COMMENT ON COLUMN soil_data.project_soil_map.remarks IS 'Additional remarks or notes';


-- ----------------------------------------------------------------------------
-- SoilMappingUnitCategory: Legend category with hierarchical subcategories
-- Links to SoilMap via rootCategory relationship (0..1)
-- Self-referencing for subcategory hierarchy
-- ----------------------------------------------------------------------------
CREATE TABLE soil_data.soil_mapping_unit_category (
    category_id         INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) PRIMARY KEY,
    soil_map_id         INTEGER REFERENCES soil_data.soil_map(soil_map_id) ON DELETE CASCADE,
    parent_category_id  INTEGER REFERENCES soil_data.soil_mapping_unit_category(category_id) ON DELETE CASCADE,
    name                TEXT NOT NULL,
    description         TEXT,
    legend_order        INTEGER,
    symbol              TEXT,
    colour_rgb          TEXT,
    remarks             TEXT
);
ALTER TABLE IF EXISTS soil_data.soil_mapping_unit_category OWNER to sis;
REVOKE ALL ON TABLE soil_data.soil_mapping_unit_category FROM sis_r;
GRANT ALL ON TABLE soil_data.soil_mapping_unit_category TO sis;
GRANT SELECT ON TABLE soil_data.soil_mapping_unit_category TO sis_r;

COMMENT ON TABLE soil_data.soil_mapping_unit_category IS 'Legend category describing soil types in a map with hierarchical subcategories (ISO 28258 SoilMappingUnitCategory)';
COMMENT ON COLUMN soil_data.soil_mapping_unit_category.category_id IS 'Unique identifier for the category';
COMMENT ON COLUMN soil_data.soil_mapping_unit_category.soil_map_id IS 'Reference to soil map - only set for root categories (rootCategory relationship)';
COMMENT ON COLUMN soil_data.soil_mapping_unit_category.parent_category_id IS 'Reference to parent category for subcategory hierarchy';
COMMENT ON COLUMN soil_data.soil_mapping_unit_category.name IS 'Name of the mapping unit category';
COMMENT ON COLUMN soil_data.soil_mapping_unit_category.description IS 'Detailed description of the category';
COMMENT ON COLUMN soil_data.soil_mapping_unit_category.legend_order IS 'Order in the map legend';
COMMENT ON COLUMN soil_data.soil_mapping_unit_category.symbol IS 'Symbol used in the map legend';
COMMENT ON COLUMN soil_data.soil_mapping_unit_category.colour_rgb IS 'RGB colour code for map display (e.g., #A52A2A)';
COMMENT ON COLUMN soil_data.soil_mapping_unit_category.remarks IS 'Additional remarks or notes';

CREATE INDEX idx_category_map ON soil_data.soil_mapping_unit_category (soil_map_id);
COMMENT ON INDEX soil_data.idx_category_map IS 'Index on soil map for root categories';

CREATE INDEX idx_category_parent ON soil_data.soil_mapping_unit_category (parent_category_id);
COMMENT ON INDEX soil_data.idx_category_parent IS 'Index on parent category for hierarchy traversal';


-- ----------------------------------------------------------------------------
-- SoilMappingUnit: Delineated polygon on a soil map
-- Links to exactly one SoilMappingUnitCategory (mappingUnit 0..* to 1)
-- ----------------------------------------------------------------------------
CREATE TABLE soil_data.soil_mapping_unit (
    mapping_unit_id     INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) PRIMARY KEY,
    category_id         INTEGER NOT NULL REFERENCES soil_data.soil_mapping_unit_category(category_id) ON DELETE CASCADE,
    explanation         TEXT,
    remarks             TEXT,
    geom                GEOMETRY(MultiPolygon, 4326) NOT NULL
);
ALTER TABLE IF EXISTS soil_data.soil_mapping_unit OWNER to sis;
REVOKE ALL ON TABLE soil_data.soil_mapping_unit FROM sis_r;
GRANT ALL ON TABLE soil_data.soil_mapping_unit TO sis;
GRANT SELECT ON TABLE soil_data.soil_mapping_unit TO sis_r;

COMMENT ON TABLE soil_data.soil_mapping_unit IS 'Delineated polygon on a soil map (ISO 28258 SoilMappingUnit feature)';
COMMENT ON COLUMN soil_data.soil_mapping_unit.mapping_unit_id IS 'Unique identifier for the mapping unit';
COMMENT ON COLUMN soil_data.soil_mapping_unit.category_id IS 'Reference to the mapping unit category (required, many-to-one)';
COMMENT ON COLUMN soil_data.soil_mapping_unit.explanation IS 'Explanation or description of the mapping unit';
COMMENT ON COLUMN soil_data.soil_mapping_unit.geom IS 'MultiPolygon geometry of the mapping unit (EPSG:4326)';
COMMENT ON COLUMN soil_data.soil_mapping_unit.remarks IS 'Additional remarks or notes';

CREATE INDEX idx_mapping_unit_category ON soil_data.soil_mapping_unit (category_id);
COMMENT ON INDEX soil_data.idx_mapping_unit_category IS 'Index on category for joining with category table';

CREATE INDEX idx_mapping_unit_geom ON soil_data.soil_mapping_unit USING GIST (geom);
COMMENT ON INDEX soil_data.idx_mapping_unit_geom IS 'Spatial index on mapping unit geometry';


-- ----------------------------------------------------------------------------
-- SoilTypologicalUnit: Soil type classification
-- Links to SoilProfile via typicalProfile (0..1 to 0..*)
-- ----------------------------------------------------------------------------
CREATE TABLE soil_data.soil_typological_unit (
    typological_unit_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) PRIMARY KEY,
    name                TEXT NOT NULL,
    classification_scheme TEXT NOT NULL,
    classification_version TEXT NOT NULL,
    description         TEXT,
    remarks             TEXT
);
ALTER TABLE IF EXISTS soil_data.soil_typological_unit OWNER to sis;
REVOKE ALL ON TABLE soil_data.soil_typological_unit FROM sis_r;
GRANT ALL ON TABLE soil_data.soil_typological_unit TO sis;
GRANT SELECT ON TABLE soil_data.soil_typological_unit TO sis_r;

COMMENT ON TABLE soil_data.soil_typological_unit IS 'Soil type classification unit (ISO 28258 SoilTypologicalUnit feature)';
COMMENT ON COLUMN soil_data.soil_typological_unit.typological_unit_id IS 'Unique identifier for the typological unit';
COMMENT ON COLUMN soil_data.soil_typological_unit.name IS 'Name of the soil typological unit';
COMMENT ON COLUMN soil_data.soil_typological_unit.classification_scheme IS 'Classification scheme used (e.g., WRB, Soil Taxonomy)';
COMMENT ON COLUMN soil_data.soil_typological_unit.classification_version IS 'Version of the Classification scheme used';
COMMENT ON COLUMN soil_data.soil_typological_unit.description IS 'Detailed description of the typological unit';
COMMENT ON COLUMN soil_data.soil_typological_unit.remarks IS 'Additional remarks or notes';


-- ----------------------------------------------------------------------------
-- SoilTypologicalUnit <-> SoilMappingUnit: Many-to-many relationship
-- representedUnit (0..*) <-> mapRepresentation (0..*)
-- Each SMU should have STU percentages summing to 100%
-- Reference: ESDB SGDBE purity concept
-- ----------------------------------------------------------------------------
CREATE TABLE soil_data.soil_typological_unit_mapping_unit (
    typological_unit_id INTEGER REFERENCES soil_data.soil_typological_unit(typological_unit_id) ON DELETE CASCADE,
    mapping_unit_id     INTEGER REFERENCES soil_data.soil_mapping_unit(mapping_unit_id) ON DELETE CASCADE,
    percentage          SMALLINT NOT NULL,
    remarks             TEXT,
    PRIMARY KEY (typological_unit_id, mapping_unit_id),
    CONSTRAINT chk_percentage_range CHECK (percentage > 0 AND percentage <= 100)
);
ALTER TABLE IF EXISTS soil_data.soil_typological_unit_mapping_unit OWNER to sis;
REVOKE ALL ON TABLE soil_data.soil_typological_unit_mapping_unit FROM sis_r;
GRANT ALL ON TABLE soil_data.soil_typological_unit_mapping_unit TO sis;
GRANT SELECT ON TABLE soil_data.soil_typological_unit_mapping_unit TO sis_r;

COMMENT ON TABLE soil_data.soil_typological_unit_mapping_unit IS 'Links typological units to mapping units with percentage composition (representedUnit/mapRepresentation). Percentages per SMU should sum to 100%.';
COMMENT ON COLUMN soil_data.soil_typological_unit_mapping_unit.typological_unit_id IS 'Reference to the soil typological unit (STU)';
COMMENT ON COLUMN soil_data.soil_typological_unit_mapping_unit.mapping_unit_id IS 'Reference to the soil mapping unit (SMU)';
COMMENT ON COLUMN soil_data.soil_typological_unit_mapping_unit.percentage IS 'Percentage of the STU within the SMU (sum per SMU should equal 100)';
COMMENT ON COLUMN soil_data.soil_typological_unit_mapping_unit.remarks IS 'Additional remarks or notes';


-- ----------------------------------------------------------------------------
-- SoilProfile -> SoilTypologicalUnit: typicalProfile relationship (0..* to 0..1)
-- ----------------------------------------------------------------------------
CREATE TABLE soil_data.soil_typological_unit_profile (
    typological_unit_id INTEGER REFERENCES soil_data.soil_typological_unit(typological_unit_id) ON DELETE CASCADE,
    profile_id          INTEGER REFERENCES soil_data.profile(profile_id) ON DELETE CASCADE,
    is_typical          BOOLEAN DEFAULT TRUE,
    remarks             TEXT,
    PRIMARY KEY (typological_unit_id, profile_id)
);
ALTER TABLE IF EXISTS soil_data.soil_typological_unit_profile OWNER to sis;
REVOKE ALL ON TABLE soil_data.soil_typological_unit_profile FROM sis_r;
GRANT ALL ON TABLE soil_data.soil_typological_unit_profile TO sis;
GRANT SELECT ON TABLE soil_data.soil_typological_unit_profile TO sis_r;

COMMENT ON TABLE soil_data.soil_typological_unit_profile IS 'Links profiles to typological units as typical profiles (typicalProfile relationship)';
COMMENT ON COLUMN soil_data.soil_typological_unit_profile.typological_unit_id IS 'Reference to the typological unit';
COMMENT ON COLUMN soil_data.soil_typological_unit_profile.profile_id IS 'Reference to the profile (typicalProfile)';
COMMENT ON COLUMN soil_data.soil_typological_unit_profile.is_typical IS 'Whether this is a typical profile for the typological unit';
COMMENT ON COLUMN soil_data.soil_typological_unit_profile.remarks IS 'Additional remarks or notes';


-- ----------------------------------------------------------------------------
-- SoilProfile -> SoilMappingUnit: profile relationship (0..*)
-- Links observed profiles to mapping units where they are located
-- ----------------------------------------------------------------------------
CREATE TABLE soil_data.soil_mapping_unit_profile (
    mapping_unit_id     INTEGER REFERENCES soil_data.soil_mapping_unit(mapping_unit_id) ON DELETE CASCADE,
    profile_id          INTEGER REFERENCES soil_data.profile(profile_id) ON DELETE CASCADE,
    is_representative   BOOLEAN DEFAULT TRUE,
    remarks             TEXT,
    PRIMARY KEY (mapping_unit_id, profile_id)
);
ALTER TABLE IF EXISTS soil_data.soil_mapping_unit_profile OWNER to sis;
REVOKE ALL ON TABLE soil_data.soil_mapping_unit_profile FROM sis_r;
GRANT ALL ON TABLE soil_data.soil_mapping_unit_profile TO sis;
GRANT SELECT ON TABLE soil_data.soil_mapping_unit_profile TO sis_r;

COMMENT ON TABLE soil_data.soil_mapping_unit_profile IS 'Links profiles to mapping units (profile relationship 0..*)';
COMMENT ON COLUMN soil_data.soil_mapping_unit_profile.mapping_unit_id IS 'Reference to the soil mapping unit (SMU)';
COMMENT ON COLUMN soil_data.soil_mapping_unit_profile.profile_id IS 'Reference to the soil profile';
COMMENT ON COLUMN soil_data.soil_mapping_unit_profile.is_representative IS 'Whether this profile is representative for the mapping unit';
COMMENT ON COLUMN soil_data.soil_mapping_unit_profile.remarks IS 'Additional remarks or notes';
