-- OBJECT: soil_data.result_spectral and observation_num
-- ISSUE: spectral result acording to reference procedure


CREATE TABLE IF NOT EXISTS soil_data.spectral_data
(
    spectral_data_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    specimen_id integer NOT NULL,
    spectrum jsonb,
    CONSTRAINT spectral_data_pkey PRIMARY KEY (spectral_data_id),
    CONSTRAINT fk_specimen FOREIGN KEY (specimen_id)
        REFERENCES soil_data.specimen (specimen_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);
ALTER TABLE IF EXISTS soil_data.spectral_data OWNER to sis;
REVOKE ALL ON TABLE soil_data.spectral_data FROM sis_r;
GRANT ALL ON TABLE soil_data.spectral_data TO sis;
GRANT SELECT ON TABLE soil_data.spectral_data TO sis_r;
CREATE INDEX IF NOT EXISTS spectral_data_specimen_id_idx ON soil_data.spectral_data USING btree (specimen_id ASC NULLS LAST) WITH (fillfactor=100);
CREATE INDEX IF NOT EXISTS spectral_data_spectrum_idx ON soil_data.spectral_data USING gin (spectrum) WITH (fastupdate=True, gin_pending_list_limit=4194304);

CREATE TABLE IF NOT EXISTS soil_data.result_spectral
(
    result_spectral_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    observation_num_id integer,
    spectral_data_id integer NOT NULL,
    value float4 NOT NULL,
    CONSTRAINT result_spectral_observation_num_id_fkey FOREIGN KEY (observation_num_id)
        REFERENCES soil_data.observation_num (observation_num_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT result_spectral_pkey PRIMARY KEY (result_spectral_id),
    CONSTRAINT fk_spectral_data FOREIGN KEY (spectral_data_id)
        REFERENCES soil_data.spectral_data (spectral_data_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);
ALTER TABLE IF EXISTS soil_data.result_spectral OWNER to sis;
REVOKE ALL ON TABLE soil_data.result_spectral FROM sis_r;
GRANT ALL ON TABLE soil_data.result_spectral TO sis;
GRANT SELECT ON TABLE soil_data.result_spectral TO sis_r;

CREATE TABLE IF NOT EXISTS soil_data.procedure_spectral
(
    spectral_data_id integer NOT NULL,
    key text NOT NULL,
    value text NOT NULL,
    CONSTRAINT procedure_spectral_pkey PRIMARY KEY (spectral_data_id, key),
    CONSTRAINT fk_spectral_data FOREIGN KEY (spectral_data_id)
        REFERENCES soil_data.spectral_data (spectral_data_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
ALTER TABLE IF EXISTS soil_data.procedure_spectral OWNER to sis;
REVOKE ALL ON TABLE soil_data.procedure_spectral FROM sis_r;
GRANT ALL ON TABLE soil_data.procedure_spectral TO sis;
GRANT SELECT ON TABLE soil_data.procedure_spectral TO sis_r;
