#!/bin/bash

###############################################
#                    Rename                   #
###############################################

echo

COUNTRY=ID
PROJ=GSNM
YEAR=2025
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                   # << EDIT THIS LINE!
OUTPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/tmp"                          # << EDIT THIS LINE!

mkdir -p "$OUTPUT_DIR"


# # Merge, using the max value when there is a overlap and sets the nodata value to -9999
# gdalwarp -r max $INPUT_DIR/JAVA/ak_0_30_mean.tif $INPUT_DIR/KALIMANTAN/ak_0_30_QRF.tif $INPUT_DIR/SUMATRA/ak_0_30_mean.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-$UD-$LD-MEAN.tif
# gdalwarp -r max $INPUT_DIR/JAVA/ak_0_30_sd.tif $INPUT_DIR/KALIMANTAN/ak_0_30_QRF_SD.tif $INPUT_DIR/SUMATRA/ak_0_30_sd.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-$UD-$LD-SDEV.tif
# gdalwarp -r max $INPUT_DIR/JAVA/ap_0_30_mean.tif $INPUT_DIR/KALIMANTAN/ap_0_30_QRF.tif $INPUT_DIR/SUMATRA/ap_0_30_mean.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-$UD-$LD-MEAN.tif
# gdalwarp -r max $INPUT_DIR/JAVA/ap_0_30_sd.tif $INPUT_DIR/KALIMANTAN/ap_0_30_QRF_SD.tif $INPUT_DIR/SUMATRA/ap_0_30_sd.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-$UD-$LD-SDEV.tif
# gdalwarp -r max $INPUT_DIR/JAVA/cec_0_30_mean.tif $INPUT_DIR/KALIMANTAN/cec_0_30_QRF.tif $INPUT_DIR/SUMATRA/cec_0_30_mean.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UD-$LD-MEAN.tif
# gdalwarp -r max $INPUT_DIR/JAVA/cec_0_30_sd.tif $INPUT_DIR/KALIMANTAN/cec_0_30_QRF_SD.tif $INPUT_DIR/SUMATRA/cec_0_30_sd.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UD-$LD-SDEV.tif
# gdalwarp -r max $INPUT_DIR/JAVA/clay_0_30_mean.tif $INPUT_DIR/KALIMANTAN/clay_0_30_QRF.tif $INPUT_DIR/SUMATRA/clay_0_30_mean.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-$UD-$LD-MEAN.tif
# gdalwarp -r max $INPUT_DIR/JAVA/clay_0_30_sd.tif $INPUT_DIR/KALIMANTAN/clay_0_30_QRF_SD.tif $INPUT_DIR/SUMATRA/clay_0_30_sd.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-$UD-$LD-SDEV.tif
# gdalwarp -r max $INPUT_DIR/JAVA/ph_0_30_mean.tif $INPUT_DIR/KALIMANTAN/ph_0_30_QRF.tif $INPUT_DIR/SUMATRA/ph_0_30_mean.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-$UD-$LD-MEAN.tif
# gdalwarp -r max $INPUT_DIR/JAVA/ph_0_30_sd.tif $INPUT_DIR/KALIMANTAN/ph_0_30_QRF_SD.tif $INPUT_DIR/SUMATRA/ph_0_30_sd.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-$UD-$LD-SDEV.tif
# gdalwarp -r max $INPUT_DIR/JAVA/sand_0_30_mean.tif $INPUT_DIR/KALIMANTAN/sand_0_30_QRF.tif $INPUT_DIR/SUMATRA/sand_0_30_mean.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-$UD-$LD-MEAN.tif
# gdalwarp -r max $INPUT_DIR/JAVA/sand_0_30_sd.tif $INPUT_DIR/KALIMANTAN/sand_0_30_QRF_SD.tif $INPUT_DIR/SUMATRA/sand_0_30_sd.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-$UD-$LD-SDEV.tif
# gdalwarp -r max $INPUT_DIR/JAVA/silt_0_30_mean.tif $INPUT_DIR/KALIMANTAN/silt_0_30_QRF.tif $INPUT_DIR/SUMATRA/silt_0_30_mean.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-$UD-$LD-MEAN.tif
# gdalwarp -r max $INPUT_DIR/JAVA/silt_0_30_sd.tif $INPUT_DIR/KALIMANTAN/silt_0_30_QRF_SD.tif $INPUT_DIR/SUMATRA/silt_0_30_sd.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-$UD-$LD-SDEV.tif
# gdalwarp -r max $INPUT_DIR/JAVA/soc_0_30_mean.tif $INPUT_DIR/KALIMANTAN/soc_0_30_QRF.tif $INPUT_DIR/SUMATRA/soc_0_30_mean.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-$UD-$LD-MEAN.tif
# gdalwarp -r max $INPUT_DIR/JAVA/soc_0_30_sd.tif $INPUT_DIR/KALIMANTAN/soc_0_30_QRF_SD.tif $INPUT_DIR/SUMATRA/soc_0_30_sd.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-$UD-$LD-SDEV.tif
# gdalwarp -r max $INPUT_DIR/JAVA/total_N_0_30_mean.tif $INPUT_DIR/KALIMANTAN/total_N_0_30_QRF.tif $INPUT_DIR/SUMATRA/total_N_0_30_mean.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-$UD-$LD-MEAN.tif
# gdalwarp -r max $INPUT_DIR/JAVA/total_N_0_30_sd.tif $INPUT_DIR/KALIMANTAN/total_N_0_30_QRF_SD.tif $INPUT_DIR/SUMATRA/total_N_0_30_sd.tif -dstnodata -9999 $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-$UD-$LD-SDEV.tif


PROJ=GSOCSEQ
YEAR=2021
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                 # << EDIT THIS LINE!

cp $INPUT_DIR/IDN_GSOCseq_AbsDiff_BAU_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_AbsDiff_SSM1_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_AbsDiff_SSM2_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_AbsDiff_SSM3_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_ASR_BAU_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_ASR_BAU_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAU-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_ASR_SSM1_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_ASR_SSM1_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_ASR_SSM2_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_ASR_SSM2_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_ASR_SSM3_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_ASR_SSM3_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_BAU_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAU-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_finalSOC_BAU_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_finalSOC_SSM1_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_finalSOC_SSM2_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_finalSOC_SSM3_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_RelDiff_SSM1_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_RelDiff_SSM2_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_RelDiff_SSM3_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_RSR_SSM1_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_RSR_SSM1_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_RSR_SSM2_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_RSR_SSM2_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_RSR_SSM3_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/IDN_GSOCseq_RSR_SSM3_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_SSM_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_SSM_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_SSM_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_GSOCseq_T0_UncertaintyMap030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/IDN_1km_GSOCseq_T0_Map030_Corr.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0-$YEAR-$UD-$LD-MEAN.tif
