#!/bin/bash

###############################################
#                    Rename                   #
###############################################

echo

COUNTRY=PH
PROJ=GSAS
YEAR=2020
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                   # << EDIT THIS LINE!
OUTPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/tmp"                          # << EDIT THIS LINE!

mkdir -p "$OUTPUT_DIR"

cp $INPUT_DIR/Top0_30ECse.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/Sub30_100ECse.tif $OUTPUT_DIR/$COUNTRY-$PROJ-ECX-$YEAR-30-100-MEAN.tif
cp $INPUT_DIR/Top0_30ESP.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXC-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/Sub30_100ESP.tif $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXC-$YEAR-30-100-MEAN.tif
cp $INPUT_DIR/Top0_30PH.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/Sub30_100PH.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-30-100-MEAN.tif
cp $INPUT_DIR/Top0_30saltaffected.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SALT-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/Sub30_100saltaffected.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SALT-$YEAR-30-100-MEAN.tif


PROJ=GSOCSEQ
YEAR=2021
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                          # << EDIT THIS LINE!

cp $INPUT_DIR/PHL_GSOCseq_AbsDiff_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_AbsDiff_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_AbsDiff_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_AbsDiff_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_ASR_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_ASR_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_ASR_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_ASR_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_finalSOC_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_finalSOC_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_finalSOC_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_finalSOC_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_RelDiff_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_RelDiff_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_RelDiff_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_RSR_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_RSR_SSM1_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1U-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/PHL_GSOCseq_RSR_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_RSR_SSM2_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2U-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/PHL_GSOCseq_RSR_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/PHL_GSOCseq_RSR_SSM3_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3U-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/PHL_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSMU-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/PHL_GSOCseq_T0_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0-$YEAR-$UD-$LD-MEAN.tif


PROJ=GSNM
YEAR=2023
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                          # << EDIT THIS LINE!

cp $INPUT_DIR/ak_0_30_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/ak_30_60_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/ap_0_30_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/ap_30_60_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/bd_0_30_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/bd_30_60_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/cec_0_30_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/cec_30_60_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/clay_0_30_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/clay_30_60_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/ocs_0_30_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/ocs_30_60_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/ph_0_30_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/ph_30_60_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/sand_0_30_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/sand_30_60_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-30-60-MEAN.tif
cp $INPUT_DIR/silt_0_30_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-0-30-MEAN.tif
cp $INPUT_DIR/silt_30_60_Mean_PHL.tif $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-30-60-MEAN.tif

# CORGSSMU -> CORGSOCSSMU
