#!/bin/bash

###############################################
#                    Rename                   #
###############################################

echo

COUNTRY=BT
PROJ=GSOCSEQ
YEAR=2022
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                   # << EDIT THIS LINE!
OUTPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/tmp"                          # << EDIT THIS LINE!

mkdir -p "$OUTPUT_DIR"

cp $INPUT_DIR/Bhutan_GSOCseq_AbsDiff_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_AbsDiff_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_AbsDiff_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_AbsDiff_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_BAU_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAU-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM1_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM2_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM3_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_BAU_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAU-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_finalSOC_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAU-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_finalSOC_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_finalSOC_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_finalSOC_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RelDiff_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RelDiff_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RelDiff_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM1_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM2_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM3_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM1-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM2-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM3-$YEAR-$UD-$LD-UNCT.tif
cp $INPUT_DIR/Bhutan_GSOCseq_T0_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Bhutan_GSOCseq_T0_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0-$YEAR-$UD-$LD-UNCT.tif


PROJ=GSNM
YEAR=2024
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                          # << EDIT THIS LINE!

cp $INPUT_DIR/AvailK_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/AvailK_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/AvailP_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/AvailP_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/BD_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BD_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/BS_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BASAT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/BS_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BASAT-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/Ca_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CAEXC-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Ca_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CAEXC-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/CEC_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/CEC_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/ClayTotal_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/ClayTotal_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/CNRatio_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CNRAT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/CNRatio_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CNRAT-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/CoarMat_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CFRAGF-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/CoarMat_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CFRAGF-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/K_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-KEXC-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/K_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-KEXC-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/Mg2_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-MGEXC-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Mg2_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-MGEXC-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/Na_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXC-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/Na_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXC-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/OC_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/OC_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/pHH2O_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-PHAQ-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/pHH2O_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-PHAQ-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/SandTotal_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/SandTotal_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/SiltTotal_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/SiltTotal_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/TEB_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BSEXC-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TEB_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BSEXC-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/TotalN_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TotalN_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/SoilType_map_10.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAWRB-$YEAR-0-0-MEAN.tif
